# Generated by Django 5.2.8 on 2025-11-25 04:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('profile_image', models.URLField(blank=True)),
                ('banner_image', models.URLField(blank=True, help_text='Artist banner image')),
                ('artist_type', models.CharField(choices=[('solo', 'Solo Artist'), ('group', 'Group'), ('band', 'Band')], default='group', max_length=20)),
                ('debut_date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('member_count', models.IntegerField(blank=True, help_text='Number of members (for groups)', null=True)),
                ('fandom_name', models.CharField(blank=True, help_text='Official fandom name', max_length=100)),
                ('official_colors', models.CharField(blank=True, help_text='Official brand colors (hex codes)', max_length=100)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('weverse_url', models.URLField(blank=True)),
                ('official_website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display categories')),
                ('image', models.URLField(blank=True, help_text='Category banner/thumbnail image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('album', 'Album'), ('photocard', 'Photocard'), ('lightstick', 'Lightstick'), ('clothing', 'Clothing'), ('poster', 'Poster'), ('seasongreeting', "Season's Greeting"), ('dvd', 'DVD/Blu-ray'), ('kithno', 'KiT/Kihno'), ('other', 'Other Merchandise')], default='album', max_length=20)),
                ('item_code', models.CharField(help_text='SKU/Barcode', max_length=50, unique=True)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price before discount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.URLField(blank=True, help_text='Main product image')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pre_order', models.BooleanField(default=False, help_text='Is this a pre-order item?')),
                ('pre_order_start_date', models.DateTimeField(blank=True, null=True)),
                ('pre_order_end_date', models.DateTimeField(blank=True, null=True)),
                ('expected_ship_date', models.DateField(blank=True, help_text='Expected shipping date for pre-orders', null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('label', models.CharField(blank=True, help_text='Record label/publisher', max_length=100)),
                ('version', models.CharField(blank=True, help_text='Album version (e.g., Member Ver., Limited Ed.)', max_length=100)),
                ('includes_random_item', models.BooleanField(default=False, help_text='Contains random photocard or item')),
                ('random_options', models.CharField(blank=True, help_text="e.g., '1 of 5 random photocards'", max_length=200)),
                ('bonus_items', models.TextField(blank=True, help_text="Bonus/gift items included (e.g., 'Unreleased photocard')")),
                ('weight_grams', models.IntegerField(blank=True, help_text='Product weight in grams', null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions (L x W x H in cm)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ecommerce.artist')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ecommerce.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='ecommerce_p_slug_b8decd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='ecommerce_p_is_feat_a92ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_trending', 'is_active'], name='ecommerce_p_is_tren_5ee840_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_pre_order', 'is_active'], name='ecommerce_p_is_pre__59ce74_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['artist', 'is_active'], name='ecommerce_p_artist__49ec2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
    ]
