# Generated by Django 5.2.8 on 2025-11-25 06:36

import django_ckeditor_5.fields
import ecommerce.models.products
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to=ecommerce.models.products.product_image_path),
        ),
        migrations.AlterField(
            model_name='artist',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Artist banner image', null=True, upload_to=ecommerce.models.products.artist_banner_path),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce.models.products.artist_profile_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category banner/thumbnail image', null=True, upload_to=ecommerce.models.products.category_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
